dependencies:
  - name: java
    version: ~2.13.1
    repository: '@hmctspublic'

  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    tags:
      - cmc-claim-store-postgresql-pod

  - name: ccd
    version: ~4.1.0
    repository: '@hmctspublic'
    condition: cmc-claim-store.claimStoreCCD.enabled
