dependencies:
  - name: java
    version: ~2.13.1
    repository: '@hmctspublic'

  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    condition: postgresql.enabled

  - name: cmc-citizen-frontend
    version: ~3.2.0
    repository: '@hmctspublic'
    condition: cmc-citizen-frontend.enabled

  - name: ccd
    version: ~3.3.1
    repository: '@hmctspublic'
    condition: ccd.enabled
