postgresql:
  enabled: false
ccd:
  enabled: false

java:
  image: hmctspublic.azurecr.io/cmc/claim-store:latest
  ingressHost: cmc-claim-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4400
  aadIdentityName: money-claims
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
        - name: claim-store-db-password
          alias: CLAIM_STORE_DB_PASSWORD
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: cmc-db-password
          alias: CMC_DB_PASSWORD
        - name: citizen-oauth-client-secret
          alias: oauth2.client.secret
        - name: claim-store-s2s-secret
          alias: idam.s2s-auth.totp_secret
        - name: anonymous-caseworker-username
          alias: idam.caseworker.anonymous.username
        - name: anonymous-caseworker-password
          alias: idam.caseworker.anonymous.password
        - name: system-update-username
          alias: idam.caseworker.system.username
        - name: system-update-password
          alias: idam.caseworker.system.password
        - name: notify-api-key
          alias: GOV_NOTIFY_API_KEY
        - name: milo-recipient
          alias: MILO_CSV_RECIPIENT
        - name: staff-email
          alias: staff-notifications.recipient
        - name: live-support-email
          alias: live-support.recipient
        - name: rpa-email-sealed-claim
          alias: rpa.notifications.sealedClaimRecipient
        - name: rpa-email-legal-sealed-claim
          alias: rpa.notifications.legalSealedClaimRecipient
        - name: rpa-email-more-time-requested
          alias: rpa.notifications.moreTimeRequestedRecipient
        - name: rpa-email-response
          alias: rpa.notifications.responseRecipient
        - name: rpa-email-ccj
          alias: rpa.notifications.countyCourtJudgementRecipient
        - name: rpa-email-paid-in-full
          alias: rpa.notifications.paidInFullRecipient
        - name: launchDarkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: sendgrid-api-key
          alias: SENDGRID_API_KEY
        - name: staff-email-legal-rep
          alias: staff-notifications.legalRecipient
  environment:
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: claim-store
    REFORM_ENVIRONMENT: preview
    SPRING_MAIL_HOST: mta.reform.hmcts.net
    SPRING_MAIL_PORT: 25
    SPRING_MAIL_TEST_CONNECTION: false
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mta.reform.hmcts.net
    CLAIM_STORE_TEST_SUPPORT_ENABLED: true
    CMC_DB_USERNAME: 'cmc@cmc-{{ .Values.global.environment }}'
    CMC_DB_HOST: cmc-{{ .Values.global.environment }}.postgres.database.azure.com
    CMC_DB_CONNECTION_OPTIONS: '?sslmode=require'
    CMC_DB_NAME: cmc
    CMC_DB_PORT: 5432
    FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
    FEATURE_TOGGLES_CTSC_ENABLED: false
    FEATURE_TOGGLES_BULK_PRINT_TRANSFER_ENABLED: false
    FEATURE_TOGGLES_STAFF_EMAILS_ENABLED: true
    FEATURE_TOGGLES_STAFF_EMAILS_ENABLED_FOR_LEGAL_REP: true
    FEATURE_AUTO_CANCEL_PAYMENTS: false
    STAFF_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    RPA_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    DOCUMENT_MANAGEMENT_USERROLES: caseworker-cmc,citizen
    MILO_CSV_SCHEDULE: ''
    MILO_CSV_SENDER: noreply@reform.hmcts.net
    SCHEDULE_STATE_TRANSITION_STAY_CLAIM: '0 0 16 ? * MON-FRI *'
    SCHEDULE_TRANSFER_CLAIMS: '0 0 12 1 * ?'
    SCHEDULE_STATE_TRANSITION_WAITING_TRANSFER: '0 0 16 ? * MON-FRI *'
    CLAIM_STAYED_SCHEDULE: ''
    ASYNC_MAX_THREADPOOL_SIZE: 50
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    PDF_SERVICE_URL: http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SEND_LETTER_URL: http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEES_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FRONTEND_BASE_URL: https://moneyclaims.{{ .Values.global.environment }}.platform.hmcts.net
    RESPOND_TO_CLAIM_URL: https://moneyclaims.{{ .Values.global.environment }}.platform.hmcts.net/first-contact/start
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOC_ASSEMBLY_URL: http://dg-docassembly-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_CLOUD_BOOTSTRAP_ENABLED: true
