tags:
  cmc-claim-store-postgresql-pod: true
  cmc-citizen-frontend-pod: true
  cmc-ccd-stack: true
  ccd-idam-pr: true
  postgresql-pod: false  # stop any subcharts starting their own postgres instance

postgresql:
  image:
    tag: '11.3.0'
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE claimstore WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE features WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  nameOverride: postgres
  persistence:
    enabled: false

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    LOG_LEVEL: DEBUG
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    SEND_LETTER_URL: http://rpe-send-letter-service-aat.service.core-compute-aat.internal
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    PDF_SERVICE_URL: http://cmc-pdf-service-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-aat.service.core-compute-aat.internal
    PAY_URL: http://payment-api-aat.service.core-compute-aat.internal
    FEES_URL: http://fees-register-api-aat.service.core-compute-aat.internal
    DOC_ASSEMBLY_URL: false
    FRONTEND_BASE_URL: https://www-${SERVICE_FQDN}
    RESPOND_TO_CLAIM_URL: https://www-${SERVICE_FQDN}/first-contact/start
    CLAIM_STORE_DB_HOST: ${SERVICE_NAME}-postgres
    CLAIM_STORE_DB_USERNAME: hmcts
    CLAIM_STORE_DB_PASSWORD: hmcts
    CMC_DB_HOST: ${SERVICE_NAME}-postgres
    CMC_DB_USERNAME: hmcts
    CMC_DB_PASSWORD: hmcts
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-data-store-api

cmc-citizen-frontend:
  nodejs:
    image: hmctspublic.azurecr.io/cmc/citizen-frontend:latest  # master
    ingressIP: ${INGRESS_IP}
    consulIP: ${CONSUL_LB_IP}
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    releaseNameOverride: ${SERVICE_NAME}-nodejs
    readinessDelay: 90  # claim-store will start much slower
    livenessDelay: 90  # claim-store will start much slower
    registerAdditionalDns:
      enabled: true
      primaryIngressHost: ${SERVICE_FQDN}
      prefix: www
    environment:
      LOG_LEVEL: DEBUG
      FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl-api
      CLAIM_STORE_URL: http://${SERVICE_NAME}-java
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
      IDAM_S2S_AUTH: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      PAY_URL: http://payment-api-aat.service.core-compute-aat.internal
      FEES_URL: http://fees-register-api-aat.service.core-compute-aat.internal
      DRAFT_STORE_URL: http://draft-store-service-aat.service.core-compute-aat.internal
      DOC_ASSEMBLY_URL: http://http://dg-docassembly-aat.service.core-compute-aat.interna
  rpe-feature-toggle-api:
    java:
      releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
      environment:
        FEATURES_DB_HOST: ${SERVICE_NAME}-postgres
        FEATURES_DB_NAME: features
        FEATURES_DB_USER_NAME: hmcts
        FEATURES_DB_PASSWORD: hmcts
      postgresql:
        image:
          tag: '11.3.0'
    importer:
      apiUrl: http://${SERVICE_NAME}-ftr-tgl-api/api/ff4j/store/features/
      kvSecretRef: kvcreds
      cron:
        enabled: false
      oneoff:
        command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_directions_questionnaire 'CMC Directions Questionnaire' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_mediation_pilot 'CMC Mediation Pilot' '1.0' &&
          /scripts/add-toggle.sh cmc_defence_reminders 'CMC defence reminders' false
        enabled: true
        permissions: cmc-new-features-consent-given
  idam-pr:
    redirect_uris:
      Money Claims - Citizen:
        - https://www-${SERVICE_FQDN}/receiver

ccd:
  enabled: true
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  postgresql:
    nameOverride: postgres
  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      CCD Admin:
        - https://admin-web-${SERVICE_FQDN}/oauth2redirect
  apiGatewayWeb:
    enabled: true
    s2sKey: ${API_GATEWAY_S2S_KEY}
    idamClientSecret:
      value: ${API_GATEWAY_IDAM_SECRET}
  managementWeb:
    enabled: true
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  ccd-admin-web:
    nodejs:
      ingressClass: traefik-no-proxy
      ingressHost: ccd-admin-web-${SERVICE_FQDN}
      secrets:
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
        disabled: false
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0


